MONTH = {
    1 : "Jan",
    2 : "Feb",
    3 : "Mar",
    4 : "Apr",
    5 : "May",
    6 : "Jun",
    7 : "Jul",
    8 : "Aug",
    9 : "Sep",
    10 : "Oct",
    11 : "Nov",
    12 : "Dec",
}

HASHTAGS = [
    "instagood",
    "photooftheday",
    "photography",
    "python",
    "instadaily",
    "picoftheday",
    "photogallery",
    "photo",
    "photographer",
    "photographylovers",
    "instagram",
    "photos",
    "ig",
    "beautiful",
    "follow", 
]